### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ArktinenKarpalo** [NimimerkinKeksiminenOnVaikeaa/ot-harjoitustyo#1]
logic/Item.java luokassa solve() funktion toiminnallisuuden voisi ehkä toteuttaa selkeämmin tekemällä jokaisesta itemistä (implication, disjunction jne.) oman luokkansa joka extendaa/implementoi itemin.

Oletan, että tarkoitus on myöhemmin toteuttaa projektiin graafinen käyttöliittymä tekstikäyttöliittymän lisäksi. UI interface on ehkä ihan hyvä idea tämän kannalta.

TextUI kannattaisi käyttää esim. tableToString funktiossa ja muissakin Javan StringBuilder-luokkaa += sijaan.

Monessa paikkaa luodaan uusi Item niin, että konstruktorin kolme viimeisintä kenttää ovat kaikki null, koodista voisi saada hieman lyhyemmän ja siistimmän luomalla Itemiin toisen konstruktorin, jossa olisi vain kaksi ensimmäistä parametriä.

Useammissa paikoissa muuttujilla on vähän epäselviä nimiä, esim. logic/Proposition.java-luokassa on yhden kirjaimen muuttujia (esim. s ja t) joista ei heti käy ilmi mitä ne tekevät. ehkäpä t-muuttujaan liittyvä toiminta kannattaisi jopa siirtää omaan selkeästi nimettyyn funktioonsa, esim. getRandomConnective. Yhden tai kahden kirjaimen muuttujia ja taikalukuja on muuallakin.

Edelliseen liittyen ovat monet funktiot monia kymmeniä tai jopa lähemmäs sata riviä pitkiä. Ongelma ei niinkään ole pituus, vaan se, että on melko vaikeaa selvittää mitä esimerkiksi Proposition-luokan sata riviä pitkä konstruktori tarkalleen tekee. Voisi miettiä edeltävän kohdan lisäksi muita keinoja selventää näiden toimintaa. Toiminnallisuutta voisi yrittää pilkkoa muihin funktioihin tai miettiä yksinkertaisempaa rakennetta, tai vähintään kommentoida vähän mitä funktiossa suurin piirtein tapahtuu.

**Comment by NimimerkinKeksiminenOnVaikeaa** [comment]
Kiitos, hyvä ja hyödyllinen koodikatselmointi (valitettavasti omastani ei voi sanoa samaa). Valtaosa ehdotuksistasi on hyviä, paria yritin jo hieman tehdäkin, mutta kyseenalaista saanko kaikkia toteutetuiksi.

_StringBuilder-luokkaa += sijaan_
Tuosta en kuitenkaan ole varma. Jos uskotaan [tätä](https://stackoverflow.com/questions/4648607/stringbuilder-stringbuffer-vs-operator/4649160#4649160), ei noilla ole teknisesti eroa. Ja mielestäni += on selkeämmän näköistä koodia.

**Comment by ArktinenKarpalo** [comment]
Luulisin että jokaisesta += tehdään oma string builderinsa, eli jos on vaikka loopissa += niin sitten jokaisella loop-kerralla tehdään uusi string builder joka buildataan.

[tällä](https://gist.github.com/ArktinenKarpalo/7d4e66550cc39161a507faaa3cb26b4c) koodilla voidaan demonstroida nopeuseroa. Pienillä merkkijonoilla (alle 1000 merkkiä) nopeuserot eivät toki kasva kovin suuriksi, mutta luulen että olisi hyvä käytäntö käyttää stringbuilderia useiden += sijaan.

**Comment by NimimerkinKeksiminenOnVaikeaa** [comment]
No, kiitos taas. Testasin myös tekemällä jar:n demo-ohjelmasta ja tulos on sama kuin suoraan Netbeansista ajettuna. Eli taidatpa olla oikeassa, ja ensimmäinen hakukoneen tarjoama stackoverflow-osuma tiedoiltaan jotenkin epätarkka (tai minä en ymmärrä jotain).

Lisätään tuo osastoon "parannukset, jotka tehdään jos ehditään" ;)
